### ISSUE TITLE
error and "Do not use this font" on vanilla osx mountain lion

### ISSUE THREAD

**Issue by jywarren** [theleagueof/junction#2]
Just installing a new system (first mac in a while) and when installing Junction off of this address, I got the following error: http://www.theleagueofmoveabletype.com/junction

![screen shot 2013-05-01 at 9 04 09 pm](https://f.cloud.github.com/assets/24359/452304/981079c8-b2dd-11e2-9a0f-74329ef64319.png)

**Comment by ngrout** [comment]
I am getting this error too.

**Comment by sursly** [comment]
Hey @jywarren and @ngrout can you try again? We should be set now. Working on Mountain Lion and Mavericks for me.

**Comment by jywarren** [comment]
Hmm, not sure how I'd test it -- would I have to uninstall Junction and re-install it?

**Comment by sursly** [comment]
@jywarren yeah that would do it. But if you were able to install it even with the error, you're probably all set. Although there are two new weights now, so yeah, maybe get the latest version :)

**Comment by jywarren** [comment]
seems to work! no errors for any of the three weights (which btw i was psyched about, super!)
